grails-app/domain/org/tros/torgo/grails/Script.groovy
package org.tros.torgo.grails

class Script {
    
    String script
    String name

    Boolean pub
    
    TorgoUser user

    static mapping = {
        script type: 'text'
    }

    static constraints = {
    }
}

grails-app/controllers/org/tros/torgo/grails/ScriptController.groovy
package org.tros.torgo.grails

import grails.converters.JSON
import grails.converters.XML
import grails.plugin.springsecurity.annotation.Secured

/**
 * TODO: see if we can merge this and HOME.
 * May require having a user login somewhere else or
 * optionally log in from this page.
 */
@Secured(['IS_AUTHENTICATED_ANONYMOUSLY'])
class ScriptController {

    def scriptService

    /**
     * Rest support for torgo and torgo/id
     *
     * With no id, a list of id + name of available
     * scripts are returned, otherwise if an id is
     * specified, the text of the script is returned
     *
     * @return
     */
    def index() {
        if(params.id != null && request.get) {
            def s = scriptService.get(params.id)
            withFormat {
                json { render s as JSON }
                xml { render s as XML }
                '*' { render s as JSON }
            }
            return
        }

        //get available scripts
        //use the scriptService to handle restrictions
        def scripts = scriptService.scripts(params)

        withFormat {
            json { render scripts as JSON }
            xml { render scripts as XML }
            '*' { respond scripts as JSON }
        }
    }
}

grails-app/views/script/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'script.label', default: 'Script')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-script" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-script" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${scriptList}" properties="['id', 'name']" />

            <div class="pagination">
                <g:paginate total="${scriptCount ?: 0}" />
            </div>
        </div>
    </body>
</html>